export const rescueStatusConfig: Record<string, { labelKey: string; color: string; bg: string }> = {
  PENDING: { labelKey: "rescueStatusPending", color: "#d97706", bg: "#fef3c7" },
  REVIEWING: { labelKey: "rescueStatusReviewing", color: "#2563eb", bg: "#dbeafe" },
  PROPOSED_ROADSIDE: { labelKey: "rescueStatusProposedRoadside", color: "#2563eb", bg: "#dbeafe" },
  PROPOSED_TOWING: { labelKey: "rescueStatusProposedTowing", color: "#ea580c", bg: "#fff7ed" },
  DISPATCHED: { labelKey: "rescueStatusDispatched", color: "#0891b2", bg: "#cffafe" },
  EN_ROUTE: { labelKey: "rescueStatusEnRoute", color: "#0891b2", bg: "#cffafe" },
  ON_SITE: { labelKey: "rescueStatusOnSite", color: "#0d9488", bg: "#ccfbf1" },
  DIAGNOSING: { labelKey: "rescueStatusDiagnosing", color: "#ea580c", bg: "#fff7ed" },
  REPAIRING: { labelKey: "rescueStatusRepairing", color: "#2563eb", bg: "#dbeafe" },
  REPAIR_COMPLETE: { labelKey: "rescueStatusRepairComplete", color: "#16a34a", bg: "#dcfce7" },
  TOWING_DISPATCHED: { labelKey: "rescueStatusTowingDispatched", color: "#0891b2", bg: "#cffafe" },
  TOWING_ACCEPTED: { labelKey: "rescueStatusTowingAccepted", color: "#16a34a", bg: "#dcfce7" },
  TOWED: { labelKey: "rescueStatusTowed", color: "#0d9488", bg: "#ccfbf1" },
  INVOICED: { labelKey: "rescueStatusInvoiced", color: "#7c3aed", bg: "#ede9fe" },
  INVOICE_SENT: { labelKey: "rescueStatusInvoiceSent", color: "#7c3aed", bg: "#ede9fe" },
  PAYMENT_PENDING: { labelKey: "rescueStatusPaymentPending", color: "#d97706", bg: "#fef3c7" },
  COMPLETED: { labelKey: "rescueStatusCompleted", color: "#16a34a", bg: "#dcfce7" },
  CANCELLED: { labelKey: "rescueStatusCancelled", color: "#dc2626", bg: "#fee2e2" },
  SPAM: { labelKey: "rescueStatusSpam", color: "#6b7280", bg: "#f3f4f6" },
};

