using System.Security.Claims;
using System.Text;
using Microsoft.AspNetCore.Authentication;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace AGMS.WebApi;

/// <summary>
/// Very simple authentication handler that validates the custom base64 token
/// generated by <see cref="AGMS.Infrastructure.Services.AuthTokenService" />.
/// It parses the payload "userId:email:fullName:expiresAt" into claims.
/// </summary>
public class SimpleTokenAuthenticationHandler : AuthenticationHandler<AuthenticationSchemeOptions>
{
    public const string SchemeName = "SimpleToken";

    public SimpleTokenAuthenticationHandler(
        IOptionsMonitor<AuthenticationSchemeOptions> options,
        ILoggerFactory logger,
        System.Text.Encodings.Web.UrlEncoder encoder,
        ISystemClock clock)
        : base(options, logger, encoder, clock)
    {
    }

    protected override Task<AuthenticateResult> HandleAuthenticateAsync()
    {
        var authHeader = Request.Headers["Authorization"].ToString();
        if (string.IsNullOrWhiteSpace(authHeader) || !authHeader.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase))
        {
            return Task.FromResult(AuthenticateResult.NoResult());
        }

        var token = authHeader.Substring("Bearer ".Length).Trim();
        if (string.IsNullOrWhiteSpace(token))
        {
            return Task.FromResult(AuthenticateResult.NoResult());
        }

        try
        {
            var payloadBytes = Convert.FromBase64String(token);
            var payload = Encoding.UTF8.GetString(payloadBytes);
            var parts = payload.Split(':', 4, StringSplitOptions.None);
            if (parts.Length != 4)
            {
                return Task.FromResult(AuthenticateResult.Fail("Invalid token payload format."));
            }

            if (!int.TryParse(parts[0], out var userId))
            {
                return Task.FromResult(AuthenticateResult.Fail("Invalid user id in token."));
            }

            var email = parts[1];
            var fullName = parts[2];
            if (!DateTime.TryParse(parts[3], null, System.Globalization.DateTimeStyles.RoundtripKind, out var expiresAtUtc))
            {
                return Task.FromResult(AuthenticateResult.Fail("Invalid expiry in token."));
            }

            if (expiresAtUtc < DateTime.UtcNow)
            {
                return Task.FromResult(AuthenticateResult.Fail("Token has expired."));
            }

            var claims = new[]
            {
                new Claim(ClaimTypes.NameIdentifier, userId.ToString()),
                new Claim(ClaimTypes.Email, email),
                new Claim(ClaimTypes.Name, fullName)
            };

            var identity = new ClaimsIdentity(claims, SchemeName);
            var principal = new ClaimsPrincipal(identity);
            var ticket = new AuthenticationTicket(principal, SchemeName);

            return Task.FromResult(AuthenticateResult.Success(ticket));
        }
        catch (FormatException)
        {
            return Task.FromResult(AuthenticateResult.Fail("Token is not valid base64."));
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "Failed to authenticate SimpleToken.");
            return Task.FromResult(AuthenticateResult.Fail("Authentication error."));
        }
    }
}

