export const ROUTER_PAGE = {
  home: "/",
  services: "/services",
  pricing: "/pricing",
  about: "/about",
  contact: "/contact",
  admin: "/admin",
  profile: "/profile",
  booking: "/booking",
  rescue: "/rescue",
  appointments: "/appointments",
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    forgotPassword: "/auth/forgot-password",
  },
  adminModules: {
    product: "/admin/product",
    unit: "/admin/unit-managerment",
    user: "/admin/user-managerment",
    appointment: "/admin/appoinment-managerment",
    category: "/admin/category",
    service: "/admin/service",
    supplier: "/admin/supplier",
    rescue: "/admin/rescue-management",
    inventory: "/admin/inventory-management",
    intake: "/admin/intake-management",
    order: "/admin/service-order-management",
  },
};
